### ISSUE TITLE
How to adjust PPT for 7950x?

### ISSUE THREAD

**Issue by valujin** [amkillam/ryzen_smu#2]
Can anyone share command to adjust PPT for 7950X? Command for Zen3 don't work, seems like SMU address have changed for PPT.

**Comment by AndreiIvanilov** [comment]
https://github.com/Cryolitia/ryzen_smu/issues/1

**Comment by amkillam** [comment]
Reverse engineering SMU commands for all Ryzen generations falls outside of the scope of this project - this is meant to be a more convenient way to use or test SMU commands. All SMU commands I could personally find and test to be working were provided in the documentation. Hopefully you found answers in the provided issue URL.
